/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CleaningCareRouteImport } from './routes/cleaning-care'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as PetTemperatureRouteImport } from './routes/pet-temperature'
import { Route as SupportRequestRouteImport } from './routes/support-request'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as JpIndexRouteImport } from './routes/jp.index'
import { Route as JpCleaningCareRouteImport } from './routes/jp.cleaning-care'
import { Route as JpContactRouteImport } from './routes/jp.contact'
import { Route as JpFaqRouteImport } from './routes/jp.faq'
import { Route as JpGettingStartedRouteImport } from './routes/jp.getting-started'
import { Route as JpHowToUseRouteImport } from './routes/jp.how-to-use'
import { Route as JpPetTemperatureRouteImport } from './routes/jp.pet-temperature'
import { Route as JpSupportRequestRouteImport } from './routes/jp.support-request'
import { Route as JpVideosRouteImport } from './routes/jp.videos'
import { Route as ProductPci01RouteImport } from './routes/product.pci01'
import { Route as QrPci01RouteImport } from './routes/qr.pci01'
import { Route as TroubleshootingIndexRouteImport } from './routes/troubleshooting.index'
import { Route as TroubleshootingWontTurnOnRouteImport } from './routes/troubleshooting.wont-turn-on'
import { Route as AdminCasesIndexRouteImport } from './routes/admin.cases.index'
import { Route as AdminCasesCaseIdRouteImport } from './routes/admin.cases.$caseId'
import { Route as JpProductPci01RouteImport } from './routes/jp.product.pci01'
import { Route as JpQrPci01RouteImport } from './routes/jp.qr.pci01'
import { Route as JpTroubleshootingIndexRouteImport } from './routes/jp.troubleshooting.index'
import { Route as JpTroubleshootingWontTurnOnRouteImport } from './routes/jp.troubleshooting.wont-turn-on'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningCareRoute = CleaningCareRouteImport.update({
  id: '/cleaning-care',
  path: '/cleaning-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const PetTemperatureRoute = PetTemperatureRouteImport.update({
  id: '/pet-temperature',
  path: '/pet-temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRequestRoute = SupportRequestRouteImport.update({
  id: '/support-request',
  path: '/support-request',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JpIndexRoute = JpIndexRouteImport.update({
  id: '/jp/',
  path: '/jp/',
  getParentRoute: () => rootRouteImport,
} as any)
const JpCleaningCareRoute = JpCleaningCareRouteImport.update({
  id: '/jp/cleaning-care',
  path: '/jp/cleaning-care',
  getParentRoute: () => rootRouteImport,
} as any)
const JpContactRoute = JpContactRouteImport.update({
  id: '/jp/contact',
  path: '/jp/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JpFaqRoute = JpFaqRouteImport.update({
  id: '/jp/faq',
  path: '/jp/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JpGettingStartedRoute = JpGettingStartedRouteImport.update({
  id: '/jp/getting-started',
  path: '/jp/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const JpHowToUseRoute = JpHowToUseRouteImport.update({
  id: '/jp/how-to-use',
  path: '/jp/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const JpPetTemperatureRoute = JpPetTemperatureRouteImport.update({
  id: '/jp/pet-temperature',
  path: '/jp/pet-temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const JpSupportRequestRoute = JpSupportRequestRouteImport.update({
  id: '/jp/support-request',
  path: '/jp/support-request',
  getParentRoute: () => rootRouteImport,
} as any)
const JpVideosRoute = JpVideosRouteImport.update({
  id: '/jp/videos',
  path: '/jp/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPci01Route = ProductPci01RouteImport.update({
  id: '/product/pci01',
  path: '/product/pci01',
  getParentRoute: () => rootRouteImport,
} as any)
const QrPci01Route = QrPci01RouteImport.update({
  id: '/qr/pci01',
  path: '/qr/pci01',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingIndexRoute = TroubleshootingIndexRouteImport.update({
  id: '/troubleshooting/',
  path: '/troubleshooting/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingWontTurnOnRoute =
  TroubleshootingWontTurnOnRouteImport.update({
    id: '/troubleshooting/wont-turn-on',
    path: '/troubleshooting/wont-turn-on',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCasesIndexRoute = AdminCasesIndexRouteImport.update({
  id: '/admin/cases/',
  path: '/admin/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCasesCaseIdRoute = AdminCasesCaseIdRouteImport.update({
  id: '/admin/cases/$caseId',
  path: '/admin/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const JpProductPci01Route = JpProductPci01RouteImport.update({
  id: '/jp/product/pci01',
  path: '/jp/product/pci01',
  getParentRoute: () => rootRouteImport,
} as any)
const JpQrPci01Route = JpQrPci01RouteImport.update({
  id: '/jp/qr/pci01',
  path: '/jp/qr/pci01',
  getParentRoute: () => rootRouteImport,
} as any)
const JpTroubleshootingIndexRoute = JpTroubleshootingIndexRouteImport.update({
  id: '/jp/troubleshooting/',
  path: '/jp/troubleshooting/',
  getParentRoute: () => rootRouteImport,
} as any)
const JpTroubleshootingWontTurnOnRoute =
  JpTroubleshootingWontTurnOnRouteImport.update({
    id: '/jp/troubleshooting/wont-turn-on',
    path: '/jp/troubleshooting/wont-turn-on',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cleaning-care': typeof CleaningCareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/getting-started': typeof GettingStartedRoute
  '/how-to-use': typeof HowToUseRoute
  '/pet-temperature': typeof PetTemperatureRoute
  '/support-request': typeof SupportRequestRoute
  '/videos': typeof VideosRoute
  '/admin/login': typeof AdminLoginRoute
  '/jp/cleaning-care': typeof JpCleaningCareRoute
  '/jp/contact': typeof JpContactRoute
  '/jp/faq': typeof JpFaqRoute
  '/jp/getting-started': typeof JpGettingStartedRoute
  '/jp/how-to-use': typeof JpHowToUseRoute
  '/jp/pet-temperature': typeof JpPetTemperatureRoute
  '/jp/support-request': typeof JpSupportRequestRoute
  '/jp/videos': typeof JpVideosRoute
  '/product/pci01': typeof ProductPci01Route
  '/qr/pci01': typeof QrPci01Route
  '/troubleshooting/wont-turn-on': typeof TroubleshootingWontTurnOnRoute
  '/jp/': typeof JpIndexRoute
  '/troubleshooting/': typeof TroubleshootingIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
  '/jp/product/pci01': typeof JpProductPci01Route
  '/jp/qr/pci01': typeof JpQrPci01Route
  '/jp/troubleshooting/wont-turn-on': typeof JpTroubleshootingWontTurnOnRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
  '/jp/troubleshooting/': typeof JpTroubleshootingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cleaning-care': typeof CleaningCareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/getting-started': typeof GettingStartedRoute
  '/how-to-use': typeof HowToUseRoute
  '/pet-temperature': typeof PetTemperatureRoute
  '/support-request': typeof SupportRequestRoute
  '/videos': typeof VideosRoute
  '/admin/login': typeof AdminLoginRoute
  '/jp/cleaning-care': typeof JpCleaningCareRoute
  '/jp/contact': typeof JpContactRoute
  '/jp/faq': typeof JpFaqRoute
  '/jp/getting-started': typeof JpGettingStartedRoute
  '/jp/how-to-use': typeof JpHowToUseRoute
  '/jp/pet-temperature': typeof JpPetTemperatureRoute
  '/jp/support-request': typeof JpSupportRequestRoute
  '/jp/videos': typeof JpVideosRoute
  '/product/pci01': typeof ProductPci01Route
  '/qr/pci01': typeof QrPci01Route
  '/troubleshooting/wont-turn-on': typeof TroubleshootingWontTurnOnRoute
  '/jp': typeof JpIndexRoute
  '/troubleshooting': typeof TroubleshootingIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
  '/jp/product/pci01': typeof JpProductPci01Route
  '/jp/qr/pci01': typeof JpQrPci01Route
  '/jp/troubleshooting/wont-turn-on': typeof JpTroubleshootingWontTurnOnRoute
  '/admin/cases': typeof AdminCasesIndexRoute
  '/jp/troubleshooting': typeof JpTroubleshootingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cleaning-care': typeof CleaningCareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/getting-started': typeof GettingStartedRoute
  '/how-to-use': typeof HowToUseRoute
  '/pet-temperature': typeof PetTemperatureRoute
  '/support-request': typeof SupportRequestRoute
  '/videos': typeof VideosRoute
  '/admin/login': typeof AdminLoginRoute
  '/jp/cleaning-care': typeof JpCleaningCareRoute
  '/jp/contact': typeof JpContactRoute
  '/jp/faq': typeof JpFaqRoute
  '/jp/getting-started': typeof JpGettingStartedRoute
  '/jp/how-to-use': typeof JpHowToUseRoute
  '/jp/pet-temperature': typeof JpPetTemperatureRoute
  '/jp/support-request': typeof JpSupportRequestRoute
  '/jp/videos': typeof JpVideosRoute
  '/product/pci01': typeof ProductPci01Route
  '/qr/pci01': typeof QrPci01Route
  '/troubleshooting/wont-turn-on': typeof TroubleshootingWontTurnOnRoute
  '/jp/': typeof JpIndexRoute
  '/troubleshooting/': typeof TroubleshootingIndexRoute
  '/admin/cases/$caseId': typeof AdminCasesCaseIdRoute
  '/jp/product/pci01': typeof JpProductPci01Route
  '/jp/qr/pci01': typeof JpQrPci01Route
  '/jp/troubleshooting/wont-turn-on': typeof JpTroubleshootingWontTurnOnRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
  '/jp/troubleshooting/': typeof JpTroubleshootingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cleaning-care'
    | '/contact'
    | '/faq'
    | '/getting-started'
    | '/how-to-use'
    | '/pet-temperature'
    | '/support-request'
    | '/videos'
    | '/admin/login'
    | '/jp/cleaning-care'
    | '/jp/contact'
    | '/jp/faq'
    | '/jp/getting-started'
    | '/jp/how-to-use'
    | '/jp/pet-temperature'
    | '/jp/support-request'
    | '/jp/videos'
    | '/product/pci01'
    | '/qr/pci01'
    | '/troubleshooting/wont-turn-on'
    | '/jp/'
    | '/troubleshooting/'
    | '/admin/cases/$caseId'
    | '/jp/product/pci01'
    | '/jp/qr/pci01'
    | '/jp/troubleshooting/wont-turn-on'
    | '/admin/cases/'
    | '/jp/troubleshooting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cleaning-care'
    | '/contact'
    | '/faq'
    | '/getting-started'
    | '/how-to-use'
    | '/pet-temperature'
    | '/support-request'
    | '/videos'
    | '/admin/login'
    | '/jp/cleaning-care'
    | '/jp/contact'
    | '/jp/faq'
    | '/jp/getting-started'
    | '/jp/how-to-use'
    | '/jp/pet-temperature'
    | '/jp/support-request'
    | '/jp/videos'
    | '/product/pci01'
    | '/qr/pci01'
    | '/troubleshooting/wont-turn-on'
    | '/jp'
    | '/troubleshooting'
    | '/admin/cases/$caseId'
    | '/jp/product/pci01'
    | '/jp/qr/pci01'
    | '/jp/troubleshooting/wont-turn-on'
    | '/admin/cases'
    | '/jp/troubleshooting'
  id:
    | '__root__'
    | '/'
    | '/cleaning-care'
    | '/contact'
    | '/faq'
    | '/getting-started'
    | '/how-to-use'
    | '/pet-temperature'
    | '/support-request'
    | '/videos'
    | '/admin/login'
    | '/jp/cleaning-care'
    | '/jp/contact'
    | '/jp/faq'
    | '/jp/getting-started'
    | '/jp/how-to-use'
    | '/jp/pet-temperature'
    | '/jp/support-request'
    | '/jp/videos'
    | '/product/pci01'
    | '/qr/pci01'
    | '/troubleshooting/wont-turn-on'
    | '/jp/'
    | '/troubleshooting/'
    | '/admin/cases/$caseId'
    | '/jp/product/pci01'
    | '/jp/qr/pci01'
    | '/jp/troubleshooting/wont-turn-on'
    | '/admin/cases/'
    | '/jp/troubleshooting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CleaningCareRoute: typeof CleaningCareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GettingStartedRoute: typeof GettingStartedRoute
  HowToUseRoute: typeof HowToUseRoute
  PetTemperatureRoute: typeof PetTemperatureRoute
  SupportRequestRoute: typeof SupportRequestRoute
  VideosRoute: typeof VideosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  JpCleaningCareRoute: typeof JpCleaningCareRoute
  JpContactRoute: typeof JpContactRoute
  JpFaqRoute: typeof JpFaqRoute
  JpGettingStartedRoute: typeof JpGettingStartedRoute
  JpHowToUseRoute: typeof JpHowToUseRoute
  JpPetTemperatureRoute: typeof JpPetTemperatureRoute
  JpSupportRequestRoute: typeof JpSupportRequestRoute
  JpVideosRoute: typeof JpVideosRoute
  ProductPci01Route: typeof ProductPci01Route
  QrPci01Route: typeof QrPci01Route
  TroubleshootingWontTurnOnRoute: typeof TroubleshootingWontTurnOnRoute
  JpIndexRoute: typeof JpIndexRoute
  TroubleshootingIndexRoute: typeof TroubleshootingIndexRoute
  AdminCasesCaseIdRoute: typeof AdminCasesCaseIdRoute
  JpProductPci01Route: typeof JpProductPci01Route
  JpQrPci01Route: typeof JpQrPci01Route
  JpTroubleshootingWontTurnOnRoute: typeof JpTroubleshootingWontTurnOnRoute
  AdminCasesIndexRoute: typeof AdminCasesIndexRoute
  JpTroubleshootingIndexRoute: typeof JpTroubleshootingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-care': {
      id: '/cleaning-care'
      path: '/cleaning-care'
      fullPath: '/cleaning-care'
      preLoaderRoute: typeof CleaningCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-temperature': {
      id: '/pet-temperature'
      path: '/pet-temperature'
      fullPath: '/pet-temperature'
      preLoaderRoute: typeof PetTemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-request': {
      id: '/support-request'
      path: '/support-request'
      fullPath: '/support-request'
      preLoaderRoute: typeof SupportRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/': {
      id: '/jp/'
      path: '/jp'
      fullPath: '/jp/'
      preLoaderRoute: typeof JpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/cleaning-care': {
      id: '/jp/cleaning-care'
      path: '/jp/cleaning-care'
      fullPath: '/jp/cleaning-care'
      preLoaderRoute: typeof JpCleaningCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/contact': {
      id: '/jp/contact'
      path: '/jp/contact'
      fullPath: '/jp/contact'
      preLoaderRoute: typeof JpContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/faq': {
      id: '/jp/faq'
      path: '/jp/faq'
      fullPath: '/jp/faq'
      preLoaderRoute: typeof JpFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/getting-started': {
      id: '/jp/getting-started'
      path: '/jp/getting-started'
      fullPath: '/jp/getting-started'
      preLoaderRoute: typeof JpGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/how-to-use': {
      id: '/jp/how-to-use'
      path: '/jp/how-to-use'
      fullPath: '/jp/how-to-use'
      preLoaderRoute: typeof JpHowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/pet-temperature': {
      id: '/jp/pet-temperature'
      path: '/jp/pet-temperature'
      fullPath: '/jp/pet-temperature'
      preLoaderRoute: typeof JpPetTemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/support-request': {
      id: '/jp/support-request'
      path: '/jp/support-request'
      fullPath: '/jp/support-request'
      preLoaderRoute: typeof JpSupportRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/videos': {
      id: '/jp/videos'
      path: '/jp/videos'
      fullPath: '/jp/videos'
      preLoaderRoute: typeof JpVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/pci01': {
      id: '/product/pci01'
      path: '/product/pci01'
      fullPath: '/product/pci01'
      preLoaderRoute: typeof ProductPci01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/pci01': {
      id: '/qr/pci01'
      path: '/qr/pci01'
      fullPath: '/qr/pci01'
      preLoaderRoute: typeof QrPci01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting/': {
      id: '/troubleshooting/'
      path: '/troubleshooting'
      fullPath: '/troubleshooting/'
      preLoaderRoute: typeof TroubleshootingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting/wont-turn-on': {
      id: '/troubleshooting/wont-turn-on'
      path: '/troubleshooting/wont-turn-on'
      fullPath: '/troubleshooting/wont-turn-on'
      preLoaderRoute: typeof TroubleshootingWontTurnOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases/': {
      id: '/admin/cases/'
      path: '/admin/cases'
      fullPath: '/admin/cases/'
      preLoaderRoute: typeof AdminCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cases/$caseId': {
      id: '/admin/cases/$caseId'
      path: '/admin/cases/$caseId'
      fullPath: '/admin/cases/$caseId'
      preLoaderRoute: typeof AdminCasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/product/pci01': {
      id: '/jp/product/pci01'
      path: '/jp/product/pci01'
      fullPath: '/jp/product/pci01'
      preLoaderRoute: typeof JpProductPci01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/qr/pci01': {
      id: '/jp/qr/pci01'
      path: '/jp/qr/pci01'
      fullPath: '/jp/qr/pci01'
      preLoaderRoute: typeof JpQrPci01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/troubleshooting/': {
      id: '/jp/troubleshooting/'
      path: '/jp/troubleshooting'
      fullPath: '/jp/troubleshooting/'
      preLoaderRoute: typeof JpTroubleshootingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/troubleshooting/wont-turn-on': {
      id: '/jp/troubleshooting/wont-turn-on'
      path: '/jp/troubleshooting/wont-turn-on'
      fullPath: '/jp/troubleshooting/wont-turn-on'
      preLoaderRoute: typeof JpTroubleshootingWontTurnOnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CleaningCareRoute: CleaningCareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GettingStartedRoute: GettingStartedRoute,
  HowToUseRoute: HowToUseRoute,
  PetTemperatureRoute: PetTemperatureRoute,
  SupportRequestRoute: SupportRequestRoute,
  VideosRoute: VideosRoute,
  AdminLoginRoute: AdminLoginRoute,
  JpCleaningCareRoute: JpCleaningCareRoute,
  JpContactRoute: JpContactRoute,
  JpFaqRoute: JpFaqRoute,
  JpGettingStartedRoute: JpGettingStartedRoute,
  JpHowToUseRoute: JpHowToUseRoute,
  JpPetTemperatureRoute: JpPetTemperatureRoute,
  JpSupportRequestRoute: JpSupportRequestRoute,
  JpVideosRoute: JpVideosRoute,
  ProductPci01Route: ProductPci01Route,
  QrPci01Route: QrPci01Route,
  TroubleshootingWontTurnOnRoute: TroubleshootingWontTurnOnRoute,
  JpIndexRoute: JpIndexRoute,
  TroubleshootingIndexRoute: TroubleshootingIndexRoute,
  AdminCasesCaseIdRoute: AdminCasesCaseIdRoute,
  JpProductPci01Route: JpProductPci01Route,
  JpQrPci01Route: JpQrPci01Route,
  JpTroubleshootingWontTurnOnRoute: JpTroubleshootingWontTurnOnRoute,
  AdminCasesIndexRoute: AdminCasesIndexRoute,
  JpTroubleshootingIndexRoute: JpTroubleshootingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
